### ISSUE TITLE
Error: Malformed UTF-8 data

### ISSUE THREAD

**Issue by Potat0000** [edolphin-ydf/hexo-encrypt#4]
输入密码后会有报错信息：Malformed UTF-8 data，请问该如何解决？
最后，这是一个完美的插件，谢谢！

**Comment by gyj1109** [comment]
抱歉，以查明原因。

**Comment by edolphin-ydf** [comment]
请问下报错影响功能使用么？我刚才测试才发现，如果密码错误，js确实会报错，不过从功能上来说，没什么影响，会考虑在后续修复这个问题。

**Comment by edolphin-ydf** [comment]
已修复，请更新后验证

**Comment by Potat0000** [comment]
另外，插件似乎对中文的支持并不好，有中文的文章节目后一片空白

**Comment by edolphin-ydf** [comment]
这。。没搞清楚你的情况，不过我的都是中文的，没有你说的问题

**Comment by Potat0000** [comment]
抱歉，上面的是打字错误，“节目”应为“解密”。问题也已解决，是模板的问题。谢谢！
