### ISSUE TITLE
无法渲染MathJax数学公式 首页能否去除加密内容

### ISSUE THREAD

**Issue by xiazeyu** [edolphin-ydf/hexo-encrypt#7]
使用Next主题
开启加密时无法正确渲染MathJax公式

首页源码中加密内容占用了大量空间，而且在首页直接解密，篇幅过长且没有TOC。
能否将加密内容在首页简单显示为“此内容已加密，点此解密”之类的？

**Comment by edolphin-ydf** [comment]
请尝试在文章中使用  `<!--more-->` 分隔需要再首页显示的内容和文章正文, `<!--more-->`之前的在首页不会加密

**Comment by xiazeyu** [comment]
@edolphin-ydf 首页的问题解决了
但是仍然无法正确渲染MathJax公式，请问有没有什么解决办法？

**Comment by xiazeyu** [comment]
贴一个在其他plugin里看到的解决方案，我会进行尝试。
https://github.com/MikeCoder/hexo-blog-encrypt/issues/22

**Comment by xiazeyu** [comment]
Fixed in:
https://github.com/edolphin-ydf/hexo-encrypt/pull/10
